### ISSUE TITLE
Timber trailer configuration.

### ISSUE THREAD

**Issue by Evdoxer** [loki79uk/FS22_UniversalAutoload#105]
Hello. Unfortunately, the manual does not describe the configuration for a logging trailer. What additional parameters should be specified in the configuration?

**Comment by loki79uk** [comment]
Hi - sorry, it is not implemented yet.  I just added the configuration option so that I can start work on implementing a log loading pattern.  I usually would not commit something until it is at least testable, but I'm working on multiple features with a few different people who are testing stuff for me so I just wanted to release the actual latest development version without trying to select certain commits and break something else.  Hopefully a full log trailer mode will be working and tested within a few weeks!

**Comment by loki79uk** [comment]
Log loading mode has been added to the base game vechicles in the latest release: 
https://github.com/loki79uk/FS22_UniversalAutoload/releases
