### ISSUE TITLE
Move the unload box away from the vehicle.

### ISSUE THREAD

**Issue by mikejl62** [loki79uk/FS22_UniversalAutoload#119]
Is there a ay to move the unload box away from the vehicle, to not be so close to the vehicle, so once you are unloaded the logs are not right up against the truck or trailer when unloaded? Because they stack up against the truck or trailer, It's hard to drive away without dragging the logs with you.

**Comment by loki79uk** [comment]
There is no way currently, but I'll add something to increase it for log trailers.  Which vechile are you having trouble with and I'll use that for testing.

**Comment by mikejl62** [comment]
Great mod by the way, Thanks

**Comment by loki79uk** [comment]
I increased the offset a bit (from `1.5*width` to `2.0*width` - but I couldn't increase it too much because then you can't reload them at all.  That was about as far as I could go and still be able to reload most of them again.  Try and see what you think: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.3.9

**Comment by mikejl62** [comment]
Thanks, That works great.
