### ISSUE TITLE
Certain Sell Points won't unload onto...

### ISSUE THREAD

**Issue by Jayshua83** [loki79uk/FS22_UniversalAutoload#133]
We have a few sell points on our map that we can't AutoUnload directly onto as it says Unload Area Not Empty or whatever.

Is that something you can tweak to be less strict about? If not what should I be looking for in the map i3d/xml that UAL finds throw that error?

**Comment by loki79uk** [comment]
If it is only happening on a certain sell point, then it is probably the flags set for the trigger(s) on the sell point.  See similar issue here:
https://github.com/loki79uk/FS22_UniversalAutoload/issues/86

Unlikely in this case, but so you are aware, it can also be due to flags set for triggers on the vehicle itself:
https://github.com/loki79uk/FS22_UniversalAutoload/issues/57
