### ISSUE TITLE
Platinum Expansion

### ISSUE THREAD

**Issue by sofr-oleg** [loki79uk/FS22_UniversalAutoload#134]
does not load - prefabwall , metall , boards.
![2022-11-29_23-40-52](https://user-images.githubusercontent.com/118161574/204644399-0746a523-471d-47bf-99bb-03010f1cc89a.png)

**Comment by loki79uk** [comment]
That trailer won't load prefab wall because it is too tall, if you want it to then you can increase the load height in your local settings:
```xml
        <vehicleConfiguration configFileName="forestryPack/vehicles/schwarzmueller/semiLowloader3A/semiLowloader3A.xml">  
            <loadingArea offset="0 0.905 -1.1" width="2.50" height="2.75" length="9.20"/>
            <loadingArea offset="0 1.285 5.35" width="2.50" height="2.75" length="3.75"/>
            <options enableRearLoading="true" enableSideLoading="true"/>
        </vehicleConfiguration>
```
 
But for me it loads all of the other things you mentioned:

![image](https://user-images.githubusercontent.com/76516343/204650059-da183cce-bd63-412d-9b89-e23b3b0ca466.png)

**Comment by sofr-oleg** [comment]
Ok.

**Comment by loki79uk** [comment]
Seems to be not a bug.  There is an argument to increase the trailer height enough to take the prefab walls, but the risk is that the trailer then becomes too top heavy with other pallets.  You can always adjust any trailer to suit your preferences.
