### ISSUE TITLE
Can't get the mod to work at all

### ISSUE THREAD

**Issue by jeff-roche** [loki79uk/FS22_UniversalAutoload#142]
Hey loki!

I've seen this mod all over the place but every time I try to use it I can't get it working.

I've tried using all of the supported base game equipment with no luck. I've attached a screenshot of what my f1 menu looks like in game. For reference I'm on the latest game version (1.8.2.0) and I ditched the mod hub version of the mod and put in the latest from here on github. I've disabled all other mods and am just using universal autoload.

What am I doing wrong?!

![20221208221130_1](https://user-images.githubusercontent.com/82384784/206616320-dcba1626-0b9f-498f-8428-f23328863b7c.jpg)

**Comment by loki79uk** [comment]
It could be that those pallets don't fit in the pickup, so try smaller pallets or a bigger trailer first.  Press ctrl-shift-F12 and you should see the pallets highlighted.

The other possible reason could just be key bindings.  Try resetting your bindings from the main menu, but if you have a lot of non standard settings then make a back up of the file first so that you can revert back to old settings.

**Comment by jeff-roche** [comment]
Keybindings were the issue. I had another mod about a year ago for logging that broke universal autoload for me and I couldn't figure out why. It was definitely the key bindings! Thank you for your help and for your awesome mods!
