### ISSUE TITLE
Autoload Lite issues

### ISSUE THREAD

**Issue by FrmrJon** [loki79uk/FS22_UniversalAutoload#161]
I'm trying to use the Autoload lite functionality, and It seems I cannot load the Platinum containers, as well as logs. Also It appears that if the trailer is set to isBaleTrailer=true, then it defaults to the full function of UAL. I'm not sure If it's meant to be like that, or if it's an issue.

**Comment by loki79uk** [comment]
Hi, thanks for the report.  Someone mentioned similar to me on Discord last week.  I've been away for a couple of weeks, but back now.

The platinum containers is not surprising because they are handled differently to deal with the auto-snapping behaviour on the platinum low loader trailers.  Likewise, I don't think logs will work until I have a mechanism to manually load them (i.e. using a wheel loader) which would need a new detection trigger to be added above the trailer.

I don't remember ever testing bale mode with autoload lite enabled, and not really thought what the default bechaviour should be.  There is a high risk that "manual loading only" will break the courseplay integration, so that is probably the main reason that I forced it to autoload normally for bale trailers.

I'll spend some time looking at this next, before I get properly started on the AD implementation.
