### ISSUE TITLE
New "ualFullTest" console command

### ISSUE THREAD

**Issue by KingArthurLV** [loki79uk/FS22_UniversalAutoload#179]
Hi @loki79uk!

First of all, thank You very much for new feature for testing loading areas. Makes life much easier.
Using this command I noticed one issue, auto bale stacking test is a bit too quick, bales are thrown so fast that they are not stacking properly, and it results in inaccurate results.

Other than that it's perfect ;)

**Comment by loki79uk** [comment]
Do you mean for round bales?  If so, then it may be not fast enough.  I need to look at this in more detail, but because the round bales start rolling as soon as you move them, then you can't stack them in this orientation without them moving all over the place.  I always use bale collection mode for stacking any bales (but especially round bales) and then it is not an issue.

**Comment by loki79uk** [comment]
I think I've cracked this in the latest release.  I did some trial and error with rotating round bales to get the centre of gravity as low as possible.  It seems to work for standard bales, but could still be an issue with mod round bales.
https://github.com/loki79uk/FS22_UniversalAutoload/releases

**Comment by KingArthurLV** [comment]
Thank You @loki79uk! I will test out new release tomorrow.
I appreciate Your work!
