### ISSUE TITLE
Ballenrichtung

### ISSUE THREAD

**Issue by acton59** [loki79uk/FS22_UniversalAutoload#187]
Hallo,

könnte man die Ballenrichtung auch für ein einzelnes Fahrzeug bestimmen.
Zur Zeit geht es nur für alle Ballen in den ModSettings

danke

**Comment by loki79uk** [comment]
> Hello,
> 
> Could you also determine the bale direction for a single vehicle. At the moment it is only possible for all bales in the ModSettings
> 
> Thanks

Hi, techinically this is possible, but I think each vehicle would need a different setting for each bale type?  What if we want to rotate small bales on a certain trailer, but not the large ones.

I assume you are using one of the rotation flags?  These are really designed for things like big-bags or pallets where you want them to face a certain direction to be accessible using a forklift.

If you do not specify either of `alwaysRotate` or `neverRotate` then the algorithm should always pick the most efficient packing direction for bales.  You can sometimes force a specific orientation for certain bales by defining the loading area width and length so that the bales will pack more efficiently in your preferred orientation (note that bales length is usually slightly shorter than 2x the width).
