### ISSUE TITLE
slow down bale loading

### ISSUE THREAD

**Issue by Toranion** [loki79uk/FS22_UniversalAutoload#202]
Is there a way that i can reduce the speed that the bales load as it's knocking bales off and messing the load. This happens in layer format

**Comment by loki79uk** [comment]
If used to load really fast for round bales, but I thought I had made everything the same speed now.  Maybe you have an old version?

Another issue could be that if they are not standard bales then you will need to define the sizes.  Normal sized bales should not collide anyway, regardless how fast you load them.

Either way, bale collection mode should work better (collisions disabled), or if you want to try slowed down then edit line 3632 to something like:  `spec.loadSpeedFactor = 0.5`

_Note: the reason for speeding up roundbale loading previously was to prevent them rolling into a new position while the next bale is loading and blocking the position of the next bale.  But now round bales should be loaded in an orientation so that they do not roll._

**Comment by loki79uk** [comment]
Did you manage to resolve this?

**Comment by loki79uk** [comment]
Closing now for housekeeping, but please re-open or contact me on Discord if you still need help!
