### ISSUE TITLE
Strap belts prevent automated sale of bales via Autodrive

### ISSUE THREAD

**Issue by Flextt** [loki79uk/FS22_UniversalAutoload#204]
Per the title. After plenty of experimentation why my bales cannot be sold at the biogas plant dropoff, I have identified the straps to be the culprit. AutoDrive does not automatically loosen them.

I am unsure which git is the better channel and how far the mods are integrated with each other as Autodrive is supposed to have UA support.

**Comment by loki79uk** [comment]
I can do that from my end.  But can you describe how are you unloading the bales with autodrive so that I can reproduce it?  I thought it uses the unload command, as in moves the bales from the trailer to a pile on the selected side?  Are you driving over the sell point without specifically unloading?

**Comment by Flextt** [comment]
I have screen-captured the issue [in this video.](https://youtu.be/BPJIalOuxS0)

The first section shows Autodrive moving towards the Feld 37 field waypoint. This triggers the CP Bale pickup sequence. After he loads some bales and gets stuck in a treeline, I let AD skip to the BGA Verkauf Ballen2 waypoint. AD creeps through the streets until I lose patience and drive most of the way manually. Then I let AD take the wheel again for the final section to the BGA Verkauf Ballen2 waypoint. AD then skips the waypoint and the bales remain unsold as I described in this issue. I cancel AD, reverse back into position, loosen the belt straps and the bales are sold.

**Comment by loki79uk** [comment]
I'm just looking at it now, can you confirm if you have unload selected in the options?
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/b01a14ee-a0cb-4c54-9102-a8b2848553d8)

The default is off:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/90c0150c-ce79-4ec9-bba2-b56a54d268d3)

**Comment by Flextt** [comment]
It was set to unload right although I wouldt have guessed that is the relevant parameter in AD.

**Comment by loki79uk** [comment]
> It was set to unload right although I wouldt have guessed that is the relevant parameter in AD.

Yes, that should do, as long as the sell trigger is to the right of the AD way point.

IAt the end of the video I think you have the wrong mode selected? It has the "load" icon in the centre instead of "unload".  Also, I think it should be blue to enable the autodetect the unload trigger.  Hold on, let me get a screenshot.

**Comment by loki79uk** [comment]
These settings are definitely working for me.  I didn't do a before picture, but there were bales and they sold:

![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/de3b26ae-4f65-4741-8e2b-935acf2aceda)
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/36553a9b-5609-4c41-bfad-2636810435a9)

**Comment by Flextt** [comment]
Cant confirm. The driver reaches the point like in the video with your suggested settings, dutifully waits his 10s, does nothing and then continues to loading point.

**Comment by loki79uk** [comment]
I just tried with the Brantner DD 24073, and that did unstrap but didn't sell with centre unloading (I assume because the load area is too high above the trigger) BUT left side unloading does work:

![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/0a902156-e5d7-4a82-b982-f9fa1f049c30)

**Comment by loki79uk** [comment]
Would you like to try with this savegame and see if it works for you?  Tab to the tractor (not the pickup) and activate autodrive should deliver the bales and then collect another load: [savegame8.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/12447733/savegame8.zip)

**Comment by Flextt** [comment]
It worked in your savegame. Did you try this in Haut Beyleron as well? The Silage sellpoint is not directly reachable for the vehicle there but unmarked and offset to the side.

**Comment by Flextt** [comment]
I will have to try again later whether or not orange or green lines change things but no time rn.

**Comment by loki79uk** [comment]
Did you get anywhere with reproducing this?  I somehow managed to break AD altogether and it would set a different destination for the unloading (instead of unloading), but I can't get it to pause there without unloading.

**Comment by Flextt** [comment]
No dice. I tried it with red dot/green line again since I saw it in your savegame and nothing happened. I am at wits end.

**Comment by loki79uk** [comment]
Maybe worth asking on the AutoDrive GitHub or Discord?  Hopefully they can help identify the issue.  I'm more than happy to fix anything in UAL if we can work out what is causing it.

**Comment by loki79uk** [comment]
There was a new AD release just now - does that make any difference?
https://github.com/Stephan-S/FS22_AutoDrive/releases/download/2.0.1.4/FS22_AutoDrive.zip

The release notes don't sound quite right, but maybe changed something with unloading:
```vehicles do not continue after unloading (pickup&delivery, combine mode) #938, 942, 946```

**Comment by Flextt** [comment]
No change in 2.0.1.4. 

I had already created a [related issue in German on the AD github](https://github.com/Stephan-S/FS22_AutoDrive/issues/974).

**Comment by TobiHH78** [comment]
Like it works for Loki, it works for me as well. I suppose it`s some kind of mod conflict.
Maybe you should post your log.

**Comment by Flextt** [comment]
Which log do you need? For Loki it has also proven to be intermittently reproducible for unknown reasons.

**Comment by loki79uk** [comment]
I don't think it was the same issue I had.  I'm pretty sure that the problem I had was just because I had set up AD wrong for a new game - whenever I tried to deliver to a location, upon arrival the destination would increment to the next destination in the list.

If you can post the log file (log.txt) from a game where you tried to deliver it may help, or even better if you could make a savegame to reproduce the issue with minimal mods and a loaded trailer in a postion close to the delivery point that would help me test it.

**Comment by TobiHH78** [comment]
@loki79uk That is, because you clicked on the unloading trailer symbol. When it`s marked "blue", it will rotate through the different unloading destinations in the folder, so after every loading, it will switch to the next unloading destination.

**Comment by Axel32019** [comment]
@Flextt Activate AD Debug "Externe Schnittstelle", try to reproduce and paste log.txt.

**Comment by loki79uk** [comment]
Have you made any progress with reproducing this?
