### ISSUE TITLE
Direction of loding pallets

### ISSUE THREAD

**Issue by alku50** [loki79uk/FS22_UniversalAutoload#205]
First thank you for this very helpful mod. As you can see on the picture some of the pallets - from the same modder -  are loading 90 deg turned to the others. It's only a matter of optic and capacity. Maybe you could give me some advice how to correct this. Or maybe  the problem is with the spec of the pallets?  (This would be the link to the LS22 Fed Produktions Pack 3.0.2.  https://www.fedaction-letsplay.de/aktuelle-projekte/ls22-nordfriesische-marsch/  )
Link to the pic uploaded:
![pallett loading](https://github.com/loki79uk/FS22_UniversalAutoload/assets/53400721/35ab7e62-e1a8-43ea-9d69-e00ebacaed1e)

**Comment by loki79uk** [comment]
I should start by saying that I am currently working on a new feature to automatically measure the size of any unknown pallets, which will make the rest of this response unnescessary.

Until that is working, there are three options to define the sizes for mod pallets:
 - You can override any settings yourself by editing the local settings file `UniversalAutoload.xml` in `%userprofile%\Documents\My Games\FarmingSimulator2022\modSettings`.
 e.g.:
 `<containerConfiguration name="FS22_HofBergmann:beerKeg" containerType="ALL" sizeX="0.625" sizeY="0.775" sizeZ="0.625"/> `

 - If it already exists in the add-on, then you can just use that, but otherwise you can make a request to add the configuration there:  `https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/issues`

 - Finally, if the original modder has got the dimensions correct in the xml, then UAL will load them from there.  However, this will not work if they have used the same filename for the i3d file as a base game pallet.  This is because it is quite common for certain pallets to simply be a re-skinned copy of a base game pallet, so by default it will assume this is the case and use the base game dimensions.
e.g. (in the xml):
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/40c41c2a-ef34-42db-881e-fcaaad3bca1a)

**Comment by alku50** [comment]
Thank you very much for your comprehensive  and quick answer. I was using your first advice. It was a lot of work but worth it as you can see it on the pic
![nice loads](https://github.com/loki79uk/FS22_UniversalAutoload/assets/53400721/aa7b9435-6170-49e9-a82b-892409083866)

**Comment by loki79uk** [comment]
Great, glad you got it working!  I should have mentioned that there is a console command: `ualImportUserConfigurations` which will load new settings without reloading the game.  I hope you found it, or can make use of it in the future!

**Comment by alku50** [comment]
Thanks again. Is there a way I can donate?Von meinem iPad gesendetAm 28.08.2023 um 19:43 schrieb Loki_79 ***@***.***>:﻿
Closed #205 as completed.
