### ISSUE TITLE
Error in console when using trailer with multiple tip sides

### ISSUE THREAD

**Issue by BurcoGames** [loki79uk/FS22_UniversalAutoload#21]
![Screenshot 2022-02-26 200706](https://user-images.githubusercontent.com/85097345/155865398-01db8249-1bfe-4ec3-a183-a3954015bbc5.png)

When entering a vehicle that has a trailer with multiple tip sides attached, the game throws an error in the console. Any changing of the tip side will cause the same error to appear (as shown in the screenshot where I switched through all the tip sides for the particular trailer). The game will also bug out and most controls will become unusable unless I manage to switch vehicle, then the problem goes away but will come back no matter what if I use the vehicle/trailer previously mentioned.

I do not have any of the "known conflict" mods, and removing only the Universal Autoload mod will cause the error to not occur. This appears to only have started happening after the 1.3 game patch.

**Comment by loki79uk** [comment]
Hi, this does make sense, but I don't know if there is anything I can do about it.  Can you please try the previous SP only version (003) and let me know if the same thing happens?

I made some changes in the latest release where the F1 menu is constantly updated while on foot, so that could explain the error.  This was not required for SP, only MP, but I added it in to both anyway for now until I can get it to work properly in MP.  It could even be related to the base game trigger box bug that I've been reading may have been re-introduced with patch 1.3.

**Comment by loki79uk** [comment]
Please ignore most of the last message, and try this version to see if it has helped: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-005

I have improved the code for the menu update, so it should only refresh whenever you move to a new vehicle.

**Comment by BurcoGames** [comment]
Just tried the new version and the same error appears. It's quite odd as to why it's doing it.

**Comment by loki79uk** [comment]
I think this error is fixed now in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-008

**Comment by BurcoGames** [comment]
Just downloaded latest and so far, no error. Issue _seems_ to be fixed. Thank you for all the work you've done, fixing this issue and for making this mod in general, this mod right now is my favorite right now and it's only going to get better from here with the updates. I'll go ahead and close this issue out. 😄
