### ISSUE TITLE
[Sugestion] More layers of bales

### ISSUE THREAD

**Issue by xxx514** [loki79uk/FS22_UniversalAutoload#212]
Hello, 
I really appreciate your mod, awesome work and great help for transporting stuff. I wondered if is there a chance to make bales autoloading in more than only one layer - and im talking about "layer" way of setting them on trailers, not "stack" method.

**Comment by loki79uk** [comment]
This is already implemented?  You can select 'layer' or 'stack', and in both modes you should get multiple bales in the trailer.  Which trailer are you having trouble with?  OR maybe you have a map with custom bales that are a different size to standard?

**Comment by xxx514** [comment]
I have DPW 1800 standard - in stacked mode indeed it takes 2 layers, but only 5 "columns" placed in center row; if switched to "layer" mode, it takes also 10 bales, but only one layer. Checked also with PWO 24 with pattern 2 (high, openable sides) which was working same way. Im using 150cm wrapped bales mostly, sometimes 150cm hay bales both round. Just made test of my dumbness if i didnt download older version, but seems to be newest 1.4.1.0. Any idea what i might done wrongly?

**Comment by loki79uk** [comment]
I've only just realised that you are talking about round bales, not square bales!!

This is a feature, but maybe not a very well documented one.  There are two ways of stacking round bales "up on end", and "laying on side".  Rather than adding a whole new option just for round bales, I cheated and used the "layer" vs "stack" to also select the stacking orientation of round bales.

STACK:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/a911974b-7878-4136-9aca-e57eafde402e)

LAYER:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/1461b7ac-d089-4125-81db-5c643ecf242c)

I do think there could be a bug here due to the calculated stack height not taking into account the offset/hexagonal packing, or maybe from the rectangular representation of the round bales (see next screenshot), which is why you only get one layer.  You can however increase the bale height to allow more layers, e.g.:
```xml
        <vehicleConfiguration configFileName="data/vehicles/kroeger/pwo24/pwo24.xml" selectedConfigs="1">
            <loadingArea offset="0 1.275 -0.20" width="2.42" height="2.20" length="9.75" baleHeight="3.8"/>
            <options isBaleTrailer="true"/>
        </vehicleConfiguration>
```
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/dcff51f0-16bb-4017-bb4d-f030273608ec)

**Comment by loki79uk** [comment]
Yes, I did some testing and it is definitly a bug.  For now that workaround works for round bales, but it would also result in square bales stacking too high.  I'll update here when I have released a fix.

**Comment by loki79uk** [comment]
I found the real cause of this - since issue #179 the round bales are rotated, so that UAL now detects collisions where it didn't before (see the angled collision boxes in the images above).

So it is not the straight forward fix that I thought, but will see what I can do without breaking something else..

**Comment by loki79uk** [comment]
Hopefully working (better) now in:  https://github.com/loki79uk/FS22_UniversalAutoload/releases/latest

Note that the default bale height for the PWO24 is still not quite enough to stack two layers of 150 bales, but if you increase to `baleHeight="3.0"` then it will.  I think the collision check still uses the position before it drops down into place, but it is certainly better.  Maybe I should increase the default bale height on a few trailers to 3m, I'll have to check how this would affect other bale sizes.  It is always the case that you optimise dimensions for stacking one item, but then it is not optimal for something else.

I do have a new method in the pipeline to detect bounding boxes for objects, so hopefully that will provide a more suitable long term solution.

**Comment by xxx514** [comment]
IDK why, but DPW1800 isnt working on newer version >.< Text says "Clogged. Cannot load anymore". For the meantime ill stay at modified previous one. No hurry in fixing, im just happy that i can help improve mod :)
![obraz](https://github.com/loki79uk/FS22_UniversalAutoload/assets/34416581/fdfdaffc-b959-4a15-9a0c-b2a28609d0e6)

**Comment by loki79uk** [comment]
Try with `UniversalAutoload.ROTATED_BALE_FACTOR = 0.75`
(you will have to edit line 17 in UniversalAutoload.lua in the mod)

You can see it is very tight with the default bale height on the 1800, so even with the new version you either have to edit the bale height, or change the ROTATED_BALE_FACTOR.  I guess 0.75 is a lot less work, but hard to justify other than "because it works"..
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/3071c048-b607-4552-a704-da7f0712eb53)

**Comment by xxx514** [comment]
Oh my, you are great! Its working! Even on modded trailer! Great! Gods bless you good sir, thanks a lot!

![obraz](https://github.com/loki79uk/FS22_UniversalAutoload/assets/34416581/31878b9f-be6f-4e82-aa15-2239a9423de6)
