### ISSUE TITLE
MP and Dedicated Server

### ISSUE THREAD

**Issue by Baseballdude1791** [loki79uk/FS22_UniversalAutoload#214]
ON Single Player the mod works like it should, but when i add the zip version after configuring trailers to my Dedi Server, nothing happens. No Debug Boxes or even options for loading...Could be a operator error, but could you help me out on this? Thanks

**Comment by loki79uk** [comment]
You shouldn't need to edit the actual mod, you can create personal configurations in the settings file on your local pc (for SP) and the server (for MP).  `...\FarmingSimulator2022\modSettings\UniversalAutoload.xml`.  The keys should work of course, but I'm pretty sure that the graphical debugging is disabled in MP since everything is calculated on the server not the client.

**Comment by loki79uk** [comment]
Closing now for housekeeping, but please re-open or contact me on Discord if you still need help!
