### ISSUE TITLE
Stuttering when unloading at sellpoints

### ISSUE THREAD

**Issue by Joe16671** [loki79uk/FS22_UniversalAutoload#218]
There is currently a map out by Stevie called MyLands4x.  It is an open map, and have found that when using Universal Autoload on this particular map there is a major drop in frame rates when unloading trailers at sellpoints with no errors in the log file.

It works fine on Stevie's other maps, and have raised this issue with him, but we are at a loss to understand why this keeps happening.

Shame really because it has performed really well, buy have had to temporarily remove it.

Hopefully you can find a solution or a reason why this is happening.

Best Regards and sincere appreciation for all your hard work on our behalf.

**Comment by loki79uk** [comment]
H, thanks for the report - I'll try to reproduce.  Does it sound the same as this issue? https://github.com/loki79uk/FS22_UniversalAutoload/issues/183

I thought I had finally solved that one, but sounds similar..  Otherwise, is it worse when on foot? or when activating the debugging display? And just to check, are you using the latest version or UAL?

Another idea to check: is there any difference in the collision mask for the sell points on that map vs one without lag?  Or does it have a lot of objects already created?

Almost certainly not related, but I have noticed unplayable lag in the base game when putting large numbers of pallets onto the train (maybe 50 or 100).  It happens completely base game with no mods, so my guess is something to do with how collisions are calculated and the fact that the train is an "immovable object".  I don't see how this translates to sell points though.

**Comment by Joe16671** [comment]
Hello.

The MyLands map has all the sellpoints around the outside perimeter of the map, with the rest of the land blank, as it is intended to build your own farm.

I have been using the latest version of your mod which I believe is 1500 same as here.  As far as I know the collision masks on this map are the same as the others, it was a new template made after the 9th November patch.  Everything seems fine on foot, just when you drive over an unloading point there is really bad stuttering for a time, then it all settles down.

This has happened with trailers containing 36, 54 and 78 pallets respectively.  As you say the more you have onboard the more lag there is.

For some reason the Autoload feature in FS22 doesn't seem as polished as previous versions, and it seems to have caused lots of lag in the game from the start.  Maybe something Giants should be looking into, but am doubtful about them doing this.

Thanks for getting back to me, I have the utmost respect for the folk who create the mods, must be hard keeping up when the developers of the game are constantly moving the goalposts.

Thanks for all your hard work and best wishes.
