### ISSUE TITLE
Can this mod fully replace the "Pallet Autoload Specialization v1.5" (aka the old autoload mod)?

### ISSUE THREAD

**Issue by Move2win** [loki79uk/FS22_UniversalAutoload#22]
Can this mod fully replace the "Pallet Autoload Specialization v1.5" (aka the old autoload mod)?

I have some trailers that were specifically modified just for "Pallet Autoload Specialization." Will those trailers still work with "UniversalAutoload" after I uninstall the "Pallet Autoload Specialization" as two autoload mods seem to be duplicated?

**Comment by BurcoGames** [comment]
Loki can provide more info on this, but from my understanding the two mods work entirely differently in how they achieve the auto-loading, so it may not be the best to run the two simultaneously. As for trailers with the specialization, those only work with that mod, but they can be converted to use with this Universal one, as referenced on the main page of the repo.

**Comment by Move2win** [comment]
Thanks for your guys' help.

Btw, I would like to ask whether cargos will snap onto the trailer in the designated layout without tension belts after being autoloaded.

For "Pallet Autoload Specialization," after the cargo has been loaded, it seems to become "free" on the trailer and starts shifting left and right when you drive if you don't apply tension belts.
Will the same happen with UniversalAutoload?

In FS19, the autoload mod FS19_EasyAutoLoad seems could "fix" the cargo onto a designated location by a preset loading layout on a trailer without using tension belts and will only "free" the cargo when I choose to unload/entirely deactivate autoload.
If UniversalAutoload can't do the same for now, will it be considered within the future update, especially for now, the tension belts has been broken by Giants.

Thank you!

**Comment by loki79uk** [comment]
I could make that happen, but I think it is a backwards step.  Once the tension belt bug is fixed, then it will not be a problem.  This "free moving pallets" is the behaviour I prefer, so that pallets can be manually unloaded (or loaded) if you want to.  The old style of fake pallets permanently attached to the trailer reduces the realism for me.

**Comment by Move2win** [comment]
> I could make that happen, but I think it is a backwards step.

I bring up this suggestion because when I was loading bales from a field, I have to frequently set tension belts on and off on and off to prevent bale shifting in the trailer when I drive from one bale to another.
Same for pallets, I have to drive very carefully if there are two columns of pallets, otherwise, it will shift, and two layers of pallets' position in the cargo trailer won't match each other.
The cargos shift in the trailer will cause difficulty when manually unloading.

> "free moving pallets" is the behaviour I prefer, so that pallets can be manually unloaded (or loaded)
pallets permanently attached to the trailer

I don't mean to create a fake animation to replace the actual cargo, which makes cargo must be auto load/unload, no manual load. I don't mean that.
If you are familiar with autoloading in FS19, you are possible to manually put your cargo on the trailer by forklift (but won't be looking so orderly), after that, you trigger the autoload, it will automatically re-placing cargos (cargos were already on the trailer) into a good looking layout and lock that layout.
For unloading, you can choose directly "unload" onto the trailer, which means just unlocking the "layout lock" without teleporting cargo onto the ground.

I have created a set of screenshots in FS19 using "FS19_EasyAutoLoad" to provide a more direct explanation.

I manually put two RESIN on the trailer but it did not looking so orderly.
![Inked771_LI](https://user-images.githubusercontent.com/45490638/155886809-2a76844c-1887-48a5-a410-13f1ba690969.jpg)

After pressing U, the autoload starts working, and the two RESIN has been "snaped" by a layout.
![Inked772_LI](https://user-images.githubusercontent.com/45490638/155886810-15ab513c-2ed5-49e3-bf8b-a6cad44ac4d5.jpg)

After pressing Y, the "layout lock" has been unlocked and cargos have been unloaded on the trailer.
If you want to unload to the ground, press B in image-2 to choose a "marker position."
![Inked773_LI](https://user-images.githubusercontent.com/45490638/155886812-db3d5e84-ec5f-44d5-a396-8190a2a59c72.jpg)

When the Autoload working mode is "ON," the RESIN will automatically layout and won't move even if the tension belts are never applied.

**Comment by loki79uk** [comment]
I can't easily do it that way because each pallet is assigned a space dynamically as it is loaded based on the positions of the other pallets.  If you manually loaded into random positions it would be very difficult to reorder them without collisions, since the other positions are unknown.  A rigid arrangement is easier, since you know the layout before you even start loading.

With my mod, the tension belts should be applied/unapplied automatically during loading, so you should not have to manually set them on and off.  I do have plans to make a 'work mode' for bales, so that it will collect any objects that are found, even when used by workers, but I have to fix all the other bugs first before creating more :D.

**Comment by Move2win** [comment]
> If you manually loaded into random positions it would be very difficult to reorder them without collisions, since the other positions are unknown.

As it does work in FS19 somehow, I believe it's still possible to do so in FS22. I think the "EasyAutoLoad" solved that issue by "set cargos to the non-collision mode when reordering" because when cargos with EasyAutoLoad work mode = ON doesn't seem to have any collision. I'm not 100% sure, but you could give it a try if you want. It might be a workaround.

> the tension belts should be applied/unapplied automatically during loading
That's definitely good to hear. But how to format cargos into a more ordered layout if one chooses to load cargos onto the trailer by a forklift manually? (format cargos will make it much easier to unload manually)

**Comment by loki79uk** [comment]
As I said earlier, I can see how it would work for a single pallet type, since all of the dimensions are known before you start.  But I don't see how I can do it for a mixed load of multiple pallet dimensions. Lets say that you were to load a stack of 3 pallets and one IBC - how would the autoloader know the correct order to reposition them?  Should it put the stack closest to the cab, or the IBC?  What if they fit next to each other side by side, but you loaded them length ways?

In the current implementation, when loading an empty trailer, the largest pallets are placed first so that smaller ones will always fit on top.  If you were to manually load them in a different order, then I would need to implement a completely new packing algorithm, that would try to preserve the current positions, but somehow line up the pallets with each other. It seems a lot of work to replace the same functionality of just performing an "unload" and "reload".
