### ISSUE TITLE
Rear Unloading ?

### ISSUE THREAD

**Issue by Ferchu425** [loki79uk/FS22_UniversalAutoload#231]
Hello, I'd like if there is something I can do to add the option of a rear unload when to a trailer, I mean.. you can choose between unloading to the right or to the left but I cant choose a "rear", is this by design? 

Im doing my test and I think Im using every option available :)

```
<vehicleConfiguration configFileName="FS22_flieglFlatbed/flieglFlatbed.xml" selectedConfigs="1" modHubId="233995">
<loadingArea offset="0 1.53 0.2" width="2.6" height="2.7" baleHeight="4.0" length="11.8"/>
<options enableRearLoading="true" enableSideLoading="true" showDebug="false" isBaleTrailer="true" horizontalLoading="true" disableHeightLimit="true" isLogTrailer="false"/>
</vehicleConfiguration>
```

Thank you!

**Comment by loki79uk** [comment]
Hi, it is limited for a few reasons.  Most trailers are "long" and it looks weird to me when you unload all the contents to the rear - either in the same orientation or rotated 90 degrees.  It is much more natural to me, and easier to judge by eye if you unload to the side.  Loading is different because it is one pallet at a time, but unloading moves the whole stacked cargo together as a block.

Another reason is that there can be unexpected conflicts of e.g. multiple trailers connected in a road train - this is already a [bug](https://github.com/loki79uk/FS22_UniversalAutoload/issues/210) and I'm looking at solutions, but it is not easy to know all situations when the rear zone should be enabled/disabled.

Less of a true reason, but more of a deterrant is that I already have the translations in all the languages for "toggle unload side" and this is how the logic is designed e.g. on the curtain trailer the curtain animations and load side are linked.  I can definitely change it to cycle around left/right/rear/front, but it is higher risk and I'll probably break some logic that I've forgotten about.

Having said that, there is `rearUnloadingOnly="true"` which is used on the pickups and utility vehicles, but this is restricted to only rear unloading (no side loading).

Finally if you are using CP or AD in conjunction with UAL then there should be options in the menus to unload at the front or rear that are not available using the key bindings.

**Comment by Ferchu425** [comment]
Thank you for the detailed answer! I must say you convinced me jeje. You are absolutely right, and the sides are more than perfect. It is just a particular use case and I can definitely live with out it

**Comment by loki79uk** [comment]
Closing as unplanned, but this idea is always in the back of my mind anyway.  It could be an option for UAL 2.0
