### ISSUE TITLE
Question regarding bale loading

### ISSUE THREAD

**Issue by ThomasBalder** [loki79uk/FS22_UniversalAutoload#25]
This is more of a question rather then an actual issue: how is the bale loading calculated, and how/what determines the max load capacity? In the current version (downloaded this morning) the loading of round bales (the 3500l / 1.25m diameter ones) is very inefficient (on the Kroeger PWO trailer). 
As you can see in the below picture, this is de default loading, only 14 bales.
![Bale loading](https://user-images.githubusercontent.com/56297954/156572700-77131d2f-cad6-4abd-afe9-50502b0a4408.png)
But as you can see in the picture below, when I move them around a bit, there's plenty of space for 28 bales.
![Bale loading 1](https://user-images.githubusercontent.com/56297954/156572708-7509841c-8242-42c4-9e5b-6ec14a1b7c50.png)

Again, not a big issue, rather a small inconvenience. So thanks for making this great mod .

**Comment by loki79uk** [comment]
Hi - it was late last night when I finished getting round bales to load, so I have not tested them on all the trailers yet.

But, the positions are calculated from the defined sizes for both the items and the available load area.

So in this case 1.3m for the bale diameter:
`<objectType name="roundbale125" sizeX="1.300" sizeY="1.200" sizeZ="1.300" flipYZ="true"/>`
and 2.30m for the trailer width:
`<loadingArea offset="0 1.275 -0.20" width="2.30" height="2.40" length="9.75"/>`

I will see if I can fine tune the values a bit to fit everything on to that trailer, but the width would need to be 2.6m as it currently stands to fit them in that arrangement.  I had to increase the bale diameters a fair bit above the expected 1.25m in order to get them to stack reliably, so maybe I can reduce it a bit, but if I increase the trailer width too much for the bales, then the pallets may overhang too far.  I'll have a look at all of the trailers with all of the different object types this evening.

**Comment by loki79uk** [comment]
I got slightly distracted by adding some new features this evening, so I'll have a look this over the weekend.  The good news is that one of the new features is to prevent loading if folded.

**Comment by ThomasBalder** [comment]
Okay, no problem! It's only a minor inconvenience with this specific trailer. New features are cool too!

**Comment by loki79uk** [comment]
I did a thing! 
![image](https://user-images.githubusercontent.com/76516343/156849486-24ab51ac-a35f-4435-bc78-224369373c2d.png)
