### ISSUE TITLE
A config to stack bales/pallets horizontally?

### ISSUE THREAD

**Issue by sadu** [loki79uk/FS22_UniversalAutoload#34]
Is there a config I can change to make the pallets/bales stack horizontally first rather than vertically?

I'm editing the SupportedVehicles.xml file to create custom heights for the trailers however the physics get really weird if I don't have that much pallets to balance it out(for eg. they stack up to 5 high).

Something of a row-major to column-major type thing?

**Comment by loki79uk** [comment]
There is nothing like that yet, as it was really designed for pallets with unknown sizes, leaving as much room as possible for other pallet types.  Bales were added later still using the same algorithm.

I am working on bale 'work mode' that could be used with workers and CP.  I'll be definitely see if I can implement horizontal first stacking as an option.

**Comment by sadu** [comment]
Ah I see, I'm fiddling with the lua code and seeing if I can write a feature in myself. Will post here if I manage to solve it. Thanks for all the amazing work you're doing, cheers!

**Comment by loki79uk** [comment]
It is currently configured around finding the next available space and then stacking that place as high as possible.  As long as you filter the items to load so that they are all the same object type/dimensions then it should be easy enough to calculate one layer, and then repeat the pattern at the next height.

One of the considerations is that you need to be able to load a save game and still continue stacking.  I think long term the best solution is to store every loaded location and pallet size in the savegame file, but I was trying to avoid that and simplify it as much as possible.  The trouble is that over-simplifying it to just 4 parameters has restricted the information available to calculate empty spaces amongst/above already loaded pallets.

**Comment by sadu** [comment]
I'm still reading through the code and not that familiar with lua so your exact logic is still not fully understood by me(but this has me interested enough). Having said that, would it be possible to just swap the logic where you increment height offset when reaching the width bounds to the length/row/distance offset increment instead (and vice versa)?

3D bin packing is a challenging task, my brain hurts when thinking about edge cases...

**Comment by loki79uk** [comment]
Horiziontal first stacking option is still planned, BUT for now this release should help to address some of the weight distribution issues: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.9.0

**Comment by loki79uk** [comment]
I'm going to shelve this idea for the time being.  It it is quite a big job to re-write all of the loading code to stack horizontally first, and there will be issues with mixed sized pallets.

I'm curently working on an automatic bale collection mode (for field work) and also hope to implement a log autoloader as well.  Maybe when everything else is done I'll come back to horizontal loading again.
