### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by skenzer** [loki79uk/FS22_UniversalAutoload#40]
Hey I just wanted to reach out and tell you how absolutely impressed I am with the universal autoload mod.   I believe this mod is very underrated. This is a game changing mod! You did an amazing job and I would like to donate to you for your efforts. Do you have anything set up for donations?

**Comment by loki79uk** [comment]
Hi, thank you for the kind words.  I'm afraid I don't have anything set up for donations, but the offer is greatly appreciated.  I'm glad you are enjoying it - I still have lots of plans to improve the loading patterns and add new features, as well as working on other mods, but 'real life' always seems to get in the way!

**Comment by skenzer** [comment]
Life has to come first :-) Thank you again for all of your time effort. If I may make one suggestion? It might be nice to be able to purchase Universal Autoload in the store much like we purchase the GPS mod or Headland Mod. Would this be possible? 
Take care and best wishes

**Comment by loki79uk** [comment]
I meant to reply to this, but I've been busy all week, especially with the new patch out.  I certainly have intentions to either make Autoload a purchasable option, or otherwise make a toggleable setting to completely disable it.

I plan to make toggleable modes, such as bale collection, horizontal stacking, normal stacking, etc so 'off' could be another mode.  It is quite a bit of work to change it though, so I'm trying to focus on my other mods again, and then come back to this one.

**Comment by loki79uk** [comment]
Closing issue - but the feature request hae been noted!
