### ISSUE TITLE
Conflict with FS22_additionalGameSettings & UniversalAutoload

### ISSUE THREAD

**Issue by mdano01** [loki79uk/FS22_UniversalAutoload#42]
There seems to be a conflict with FS22_additionalGameSettings and UniversalAutoload that appeared with the latest beta update. The crosshairs seem to be replaced with a gui object (see attached picture for reference). I tested it by limiting it down to the Map I was on,  additionalGameSettings and UniversalAuto as the only mods loaded. FS22_additionalGameSettings was from the official modhub.
![UniversalAutoload_Error](https://user-images.githubusercontent.com/43209095/164568619-fdfce78b-5b8f-4cb6-af10-42602c2fe073.png)

**Comment by loki79uk** [comment]
Hopefully fixed in this version: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.1.1-beta

I have not fully tested, but it removed the box for me.  If still not fixed for you, as a workaround you can disable TrailerHUD in the advanced game settings menu. I need to go to work now, but let me know how it goes and I'll work on it more over the weekend!

**Comment by loki79uk** [comment]
Glad this is working too - I'm slowly working through all the new bugs! 😀
