### ISSUE TITLE
Balancing trailers

### ISSUE THREAD

**Issue by Steel-Horse** [loki79uk/FS22_UniversalAutoload#54]
Is it possible to have an option to start loading from the rear or simply flip the z axis. Lets be clear I love this mod. The issue I am having is that I am using a trailer with a longish tray and tandem axles set well back. I have defined the load area to accomodate large bales and pallets. If i go to load heavy pallets, say canola oil, the default stacking gives me a double row 5 pallets high at the drawbar which is some 5m forward of the axles and makes the whole rig really unstable. In this situation if I could force loading from the back stability would improve. Either that or an option to define a second load area cube and switch on keystroke between the two.

**Comment by loki79uk** [comment]
I am looking at re-writing the loading code with more options such as horizontal first packing and maybe even multiple zones.  Loading the rear with heavy objects can give different handling issues as well.  I think it would have to be user selectable though, since at the time of loading it is not possible to know the expected total quantity of pallets, only the number currently in range.

**Comment by Steel-Horse** [comment]
Looking forward to it. If there is anything at all I can do to help just let me know. My coding skills are beginner level but I am learning. Testing and problem solving much stronger.

**Comment by loki79uk** [comment]
Duplicate of #34.  Closing for housekeeping, but this is still on my list of stuff that needs doing!
