### ISSUE TITLE
Trying to setup a mod

### ISSUE THREAD

**Issue by krambc** [loki79uk/FS22_UniversalAutoload#73]
Hi, i'm trying to add autoload to a mod and i'm having problems.

I've added the following code:
`	<universalAutoLoad>
		<vehicleConfigurations>
			<vehicleConfiguration>
				<loadingArea offset="0 0.481 -0.75" width="1.6" height="1.8" length="2.2"/>
				<loadingArea offset="0 0.481 -2.67" width="1.25" height="1.8" length="1.6"/>				
			<options isBoxTrailer="true" noLoadingIfFolded="true" enableRearLoading="true" enableSideLoading="false" zonesOverlap="true" showDebug="true" />
			</vehicleConfiguration>
		</vehicleConfigurations>
	</universalAutoLoad>`

Ass I understand it, this code may disable side loading and enable rear loading only when the rear doors are open (unfolded)

But the loading area doesn't change although I change the options.
![fsScreen_2022_07_21_12_07_40_ScreenshotMode](https://user-images.githubusercontent.com/25364738/180189145-a3ad061a-2240-401e-b241-42716c150571.png)

**Comment by loki79uk** [comment]
I'm not quite sure what you are trying to achieve?

The way you have it there, you have two loading areas that are always active:
			`<loadingArea offset="0 0.481 -0.75" width="1.6" height="1.8" length="2.2"/>`
			`<loadingArea offset="0 0.481 -2.67" width="1.25" height="1.8" length="1.6"/>`

Then you have global options for the whole trailer:
			`<options isBoxTrailer="true" noLoadingIfFolded="true" enableRearLoading="true" enableSideLoading="false" zonesOverlap="true" showDebug="true"/>`

noLoadingIfFolded will apply to both zones, and when allowed it will try to load the first zone, and then the second if there is any room.  Because of zonesOverlap="true" it will not load bales when moving.  enableRearLoading is for the manual loading (by hand or by forkift).

I have anew feature (not released yet) that will unload to the rear (instead of the side) if that is what you want?

**Comment by krambc** [comment]
Thank you for your answer.

And its posible to load from the rear only?

**Comment by loki79uk** [comment]
Yes, is this more like what you are after:
![image](https://user-images.githubusercontent.com/76516343/180321978-62ed1733-aeee-42a6-b146-48992de01b2e.png)

**Comment by krambc** [comment]
Yes!

**Comment by loki79uk** [comment]
Try this release: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.0.0-candidate-002

And use the setting:  `<options rearUnloadingOnly="true"/>`

**Comment by loki79uk** [comment]
I hope that worked for you. I'm going to close this now for housekeeping, but please re-open if you have any problems.

**Comment by krambc** [comment]
Yes. It works fine! Thank you
