### ISSUE TITLE
Loading Horizontal then Vertical?

### ISSUE THREAD

**Issue by Jayshua83** [loki79uk/FS22_UniversalAutoload#83]
Is there any chance to have an option for loading trailers horizontal and then vertical?

We are running a bit larger capacity pallets and UAL will stack them real high on one side of the trailer and causing it to tip real easily! :(

**Comment by loki79uk** [comment]
It is on my list of things to do, but there are a few other things that I would like to get done first - especially loading logs and getting the bale collection mode to work with CP.  Which trailer is it that you are having trouble with, and what settings are you using?  You could try setting a lower height as a workaround for now, or even try with two loading zones, so that it starts nearer the middle and then fills in at the front.

**Comment by loki79uk** [comment]
I finally made some progress on horizontal loading today!  Needs some refinement, but it is a really popular feature request, so I'm excited to get it into the next release soon..
![image](https://user-images.githubusercontent.com/76516343/192165084-25f3adff-d911-4da9-a87b-559a901e9836.png)

**Comment by loki79uk** [comment]
Please try this release: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.2.9

Note: You will need to set a key binding for "toggle horizontal loading"
