### ISSUE TITLE
Cant Unload bales into sale trigger

### ISSUE THREAD

**Issue by Gariot** [loki79uk/FS22_UniversalAutoload#86]
Hey!

I am playing on the No mans Land map and using the FS22_Bailey_Bale_Pallet_Trailer together with the Universal Autoload Modhub Addon and so far its working as intended. I loaded some bales and wanted to unload them right into the trigger. But for some reason i cant unload them there. I attached two pictures. I can unload on the right side, but not on the left side. Is there anything i can do to fix this? I am using the latest Modhub version.

![20220821022107_1](https://user-images.githubusercontent.com/18175983/185770367-d6a17125-8334-4bc3-b3b4-cd1d47b8c05f.jpg)

![20220821022112_1](https://user-images.githubusercontent.com/18175983/185770368-4622ef67-404a-4a39-b1b7-ba266a0cf613.jpg)

**Comment by loki79uk** [comment]
Hi, this looks like there are the wrong collision flags set on the sell point trigger.  if you press F5 to toggle through the game visual debug options, I think that there will be an invisible object over the sell point.

**Comment by Gariot** [comment]
You might be right. Now i have to find out how to fix this on my own :D

![20220821141710_1](https://user-images.githubusercontent.com/18175983/185790531-fb2df084-0714-49cb-b6fd-82c52034cd79.jpg)

**Comment by loki79uk** [comment]
If you can open the map in GE and find the sell point, then look at the which collisions are set, you should untick any of:
`CollisionFlag.STATIC_WORLD = 1`
`CollisionFlag.DYNAMIC_OBJECT = 12`
`CollisionFlag.VEHICLE = 13`
`CollisionFlag.PLAYER = 14`

**Comment by Gariot** [comment]
Thanks for the tip.

Looks like i cant fix it sadly. I turned off the collisions where it made sense but it didnt help (or i did it wrong, who knows). Not the end of the world.
But i have to say i dont really understand why theres even a collision check when unloading. I mean if i am too stupid to realize theres no place then its my fault when i unload it xD

**Comment by loki79uk** [comment]
I'll try to test it out next time I'm at my pc.  It has to detect the ground and buildings etc during unloading, otherwise pallets will spawn underground, inside buildings, or can trap players, etc.

**Comment by Gariot** [comment]
Hm, you could just let them spawn relativ to the trailer positions height plus a little extra in the air. This saves checks and is pretty much safe i believe. 
If they spawn in a player or a buildings... well, thats user error :D But i am sure i can "reload" everything, even when its in a building and not too far away.

**Comment by loki79uk** [comment]
It isn't really that simple, since the "ground" level can include pavements or hard standings that are part of buildings, or perhaps you want to unload onto another trailer or vehicle, etc.  The collision check will also prevent pallets from occupying the same position when unloading twice (e.g. unloading one fill type or pallet type followed by another).

If you want to try, you can edit the code yourself to unload anywhere - just edit the function `testUnloadLocationIsEmpty` on line 3046 to always return true.  You could also report the issue to the map creator, they just need to set the correct collision flags.  Usually it is a copy and paste error where they have used e.g. `13 = VEHICLE` instead of `21 = TRIGGER_VEHICLE`, or `14 = PLAYER` instead of `20 = TRIGGER_PLAYER`.

**Comment by loki79uk** [comment]
I found it - it is the bale trigger in the sellingStationFarmShop where the collision mask has bit 12 set:
![image](https://user-images.githubusercontent.com/76516343/186020607-18859793-c827-4842-96ab-8089a5b2518a.png)

**Comment by Gariot** [comment]
Thank you very much. I must have overlooked that one, im sorry. It is working now.

I am closing this now, Sorry for the inconvenience.
