### ISSUE TITLE
Bales orientation

### ISSUE THREAD

**Issue by DrewCZ** [loki79uk/FS22_UniversalAutoload#88]
Hi, on some version was changed loaded bales orientation. Please check this screen from 02.06.2022 here:

![obrazek](https://user-images.githubusercontent.com/26751314/185811776-6186d146-7e02-4c32-ae60-12c59faee792.png)
 24 bales loaded in this case. 
Now the bales are loaded 90° rotated and the trailer loads only 10 bales with the same configuration. 

![obrazek](https://user-images.githubusercontent.com/26751314/185812049-12adea8f-62c7-457c-be4d-e62c45fefccd.png)

Is possible to write back that first option? IMHO is very important to load bales horizontally first (mentioned here: #83 ).

Thank you! And thank you so much for your hard work!

**Comment by loki79uk** [comment]
Hi, I think that this is similar to #75.

It looks like the area is not defined correctly - it should be three bales high regardless of the orientation.  Why is there only one stack of three bales in the first image?

The second orientation should only be selected when there is no difference in the calculated packing, otherwise it should choose the orientation with the most bales.  Can you post a link to the trailer mod that you are using, and the settings if you know them (or is it from the add-on?).

Another option is to put `neverRotate = "true"` in your local settings for those bales, but that will apply to all trailers. and better to solve it using the correct dimensions for the trailer if possible.

**Comment by DrewCZ** [comment]
Hi Loki, thank you so much for your answer and care. 
The trailer has defined (include baleHeight) many many weeks ago in FS22_UniversalAutoloadModhubAddon settings. The name of the package is "FS22_lizardTrailerPack.zip" and was very tuned with me and ddewar. If you remember, there was an issue with the height of the bottom side of the UAL "box" upon the trailer bed, and that is why you can see that third stack on the end of the "older" trailer. Already solved. 
So, I'll try to redefine the UAL box again and test it. Is it an issue, if the box is defined wider than the trailer? 
And thank you for the link to issue 75. It's very inspiring.

**Comment by loki79uk** [comment]
To stack 180 square bales as before you will need to use the latest release:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.1.6

And also change the settings to the following:
```
	<vehicleConfiguration configFileName="FS22_lizardTrailerPack/lizardD616.xml" selectedConfigs="7,8">
            <loadingArea offset="0 1.52 0.48" width="2.42" height="1.70" length="7.25" baleHeight="2.50"/>
            <options enableSideLoading="true"/>
        </vehicleConfiguration>
```

![image](https://user-images.githubusercontent.com/76516343/185993395-4dd33d7d-017b-4d00-b9f3-c057a3efb697.png)

**Comment by DrewCZ** [comment]
it works! 👍  thank you for the quick fix
