### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by judg393** [loki79uk/FS22_UniversalAutoload#90]
Hi Loki me again 

Can I be a right pain in the neck. What do you mean by logs will load vertically? 

They'll stand on end rather than lying flat against the trailer bed?

**Comment by loki79uk** [comment]
Yes, that is how they load currently.  It is still a work in progress and just the orientation that they happened to be defined in (it makes sense for trees).  Most trailers wing load them because the loading volume is not tall enough, of you want too try it, make the height 4 or 5m (i.e. taller than the logs you want to load).

**Comment by judg393** [comment]
Ok any suggestions for a trailer to test?

**Comment by loki79uk** [comment]
I was using one of the base game bale trailers, but any should work as long as there are open.  Use easy dev or power tools to spawn a load of logs and see if you can break anything trying to load them!
