### ISSUE TITLE
How to load pallets defined by another mod as "EURO_PALLET", but with "very different" dimensions?

### ISSUE THREAD

**Issue by vitalii2011** [loki79uk/FS22_UniversalAutoload#92]
![fsScreen_2022_08_26_01_34_11](https://user-images.githubusercontent.com/41552153/186888702-797c31cd-cbad-49a3-807a-2347f60fbb3f.png)
This is "BAUMSTAMMPALETTE" from the BDM Produktions Pack https://www.bd-modding.de/post/bdm-produktions-pack . Or how to at least deploy it along the trailer?

**Comment by loki79uk** [comment]
Have a look in the local settings file and there is a commented out example of how to use a mod container.  There is a bit of work involved to measure or guess the dimensions, but you can use the reload settings console command to adjust them without restraint the game.  Turn on debugging mode to view the dimensions. I'm away so only on my phone, but hopefully @ddewar will be along soon to help!

**Comment by vitalii2011** [comment]
Before asking - of course, I tried to set it up, but nothing happened. 
Don't worry, it's not that important.

**Comment by ddewar** [comment]
Can you post what you've tried? Happy to take a look at this in a few hours.

**Comment by vitalii2011** [comment]
![Image 001](https://user-images.githubusercontent.com/41552153/186980695-420b9656-f37e-4d95-a2d3-317af21bf66b.png)

**Comment by ddewar** [comment]
So some good news and some bad news, 

![image](https://user-images.githubusercontent.com/15822357/187039917-30f1c434-e2fd-4078-9a8a-d62a6c9f54a6.png)

Good news, add this to you UniversalAutoload.xml in mod settings to get autoload correctly for all pallets with that pack

```
<universalAutload>
  <containerConfigurations>
          <containerConfiguration name="FS22_BDM_Produktionspack:baumstammpalette" containerType="EURO_PALLET" sizeX="6.0" sizeY="0.8" sizeZ="0.8"/>
          <containerConfiguration name="FS22_BDM_Produktionspack:emptypallet" containerType="EURO_PALLET" sizeX="1.25" sizeY="1.16" sizeZ="0.82"/>
          <containerConfiguration name="FS22_BDM_Produktionspack:bretter" containerType="EURO_PALLET" sizeX="3.0" sizeY="0.97" sizeZ="0.82"/>
          <containerConfiguration name="FS22_BDM_Produktionspack:kantholzer" containerType="EURO_PALLET" sizeX="3.0" sizeY="0.97" sizeZ="0.82"/>
          <containerConfiguration name="FS22_BDM_Produktionspack:karton" containerType="EURO_PALLET" sizeX="1.25" sizeY="1.16" sizeZ="0.82"/>
          <containerConfiguration name="FS22_BDM_Produktionspack:kiste" containerType="EURO_PALLET" sizeX="1.25" sizeY="0.95" sizeZ="0.82"/>
  </containerConfigurations>
</universalAutoLoad>
```

Bad news, you'll have to edit the mod if you want this pallet to load correctly. Looks like the center is defined wrong: 
![image](https://user-images.githubusercontent.com/15822357/187039112-3f3edc79-64dc-4681-861e-c6e28ab5a2bf.png)


You were on the right track with what you had defines, but I think your contain type was not valid. I'm not sure @loki79uk has implemented custom container types yet. (Mainly due to translations around them) If you do not like these being in Europallet, you can always use ```All``` as the container type 

Let me know if you have any more questions. Happy pallet stacking!

**Comment by ddewar** [comment]
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/discussions

For reference

**Comment by vitalii2011** [comment]
> Happy pallet stacking! 
Thank you very much for your attention to this issue and help!

**Comment by loki79uk** [comment]
Closing on the advice of @ddewar.  Please feel free to message me or re-open if there are any related issues.
